### ISSUE TITLE
Deploy to Digital Ocean is Broken

### ISSUE THREAD

**Issue by chrisvella** [digicoop/kaiwa-server#2]
Hi

I just tried to automatically deploy the server to digital ocean based on your instructions, but the server is not running. All docker images seemed to be installed, but only the ldap and postgres server seemed to be listening on any ports.

Thanks

**Comment by zmoazeni** [comment]
I ran into the same problem. I tried creating a droplet with 512MB and kept seeing processes killed due to out of memory errors by looking at /var/log/syslog

I think kaiwa needs to run on 1GB+.

**Comment by sebu77** [comment]
Yes, Prosody+Kaiwa needs to run on 1GB+ droplet
