### ISSUE TITLE
LDAP config assumption wrong for freeIPA

### ISSUE THREAD

**Issue by kevin-fibich** [digicoop/kaiwa-server#4]
All config templates show ou=groups and ou=users as root node for objects but freeIPA uses cn=users and cn=groups.

It should be possible to pass user and group basedn seperately and without any prior assumptions about their structure.

**Comment by nickbroon** [comment]
I'd agree. I'd like to use `ou=People,` as the user basedn, but currently the docker script assumes `ou=users,`.
