### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by ottersfish** [digicoop/kaiwa-server#7]
Hello I am sry if this issue off topic. I am a bit confused with the docker installation.
When installing ldap server I should execute command ldapadd -h localhost -x -D cn=admin,dc=myorga -w mypassword -f users.ldif
instead i run into problem command not found.
I followed the instruction as it is without no change. Do i miss something or this is docker issue? This is my first time using docker.

Thanks in advance!

**Comment by furkanmustafa** [comment]
You should install a package called `ldap-utils` (or similar depending on your linux distro)
